export class Products{
    public product_data=[
     {
    product_id:'1',
    product_image: "assets/img/bluesaphire.jpg",  
    product_title:'Blue Saphire Stone',
    product_price:1200,
    product_ship:30,
    product_offer:'1350',
    product_disc:'30% off',
    product_details:'Blue Sapphire is Birthstone for September month.Blue Sapphire is liked for its Pure Blue hue & good durability.Blue Sapphire or simply Sapphire is a Precious Stone, called Neelam in Hindi.',
    product_return:'If you are not satisfied with this product,return it for a refund.we will always care our customer..!',
    product_weight:'The model(weight 3kg)',
    product_material:' Hard-Material' },
     {
    product_id:'2', 
    product_image: "assets/img/emreald.jpeg",
    product_title:" Emerald Stone",
    product_price: 1350,
    product_ship: 30,
    product_offer: 1450,
    product_disc:'30% off',
    product_details:'Emerald (variety of Beryl mineral species) is a Precious Green Gemstone, called Panna in Hindi.Emerald stone is liked for its Pure Green hue.Emerald is Birthstone for May month.',
    product_return:'If you are not satisfied with this product,return it for a refund.we will always care our customer..!',
    product_weight:'The model(weight 3kg)',
    product_material:' Hard-Material' },
     { 
    product_id:'3',
    product_image: "assets/img/ruby.jpeg",
    product_title:'Ruby Stone',
    product_price: 1330,
    product_ship: 30,
    product_offer: 1550,
    product_disc:'30% off',
    product_details:'Ruby (Variety of Corundum mineral species) is a Precious Red Gemstone, called Manik in Hindi.Ruby comes in Pure Red hue (Pigeon Blood color) or various Tones of Red.Ruby Gemstone is liked for its Pure Red hue unlike seen in any other Gemstone Ruby is Birthstone of July month & is associated with Sun planet in Indian Astrology.',
    product_return:'If you are not satisfied with this product,return it for a refund.we will always care our customer..!',
    product_weight:'The model(weight 3kg)',
    product_material:' Hard-Material'},
     { 
    product_id:'4',
    product_image: "assets/img/cats.jpg",
    product_title:'Cat’s Eye',
    product_price: 1230,
    product_ship: 30,
    product_offer:1350,
    product_disc:'30% off',
    product_details:'Cat’s Eye (Chatoyancy) is an Optical Phenomenon seen in few Gemstones.Stones with this effect are called Cats Eye stone, like Quartz Cats Eye, Chrysoberyl Cats Eye & Apatite Cats Eye.Cats Eye stones are commonly used for Astrological & Ornamental purpose.',
    product_return:'If you are not satisfied with this product,return it for a refund.we will always care our customer..!',
    product_weight:'The model(weight 3kg)',
    product_material:' Hard-Material' },
     {
    product_id:'5',
    product_image: "assets/img/Hessonite.jpg",
    product_title:'Hessonite Stone',
    product_price: 1530,
    product_offer: 1680,
    product_ship: 30,
    product_disc:'30% off',
    product_details:'Hessonite Garnet Stone Price range starts at around Rupees 200/-  ($ 5) per carat and go up to Rupees 2,500/- ($ 40) per Carat as per the quality. (Color, Clarity, Cut, Shape)',
    product_return:'If you are not satisfied with this product,return it for a refund.we will always care our customer..!',
    product_weight:'The model(weight 3kg)',
    product_material:' Hard-Material' },
     {
    product_id:'6', 
    product_image: "assets/img/White-Opal.png",
    product_title:'White-Opal Stone',
    product_price: 1750,
    product_offer: 2500,
    product_ship: 30,
    product_disc:'30% off',
    product_details:'Opal Gemstone displays beautiful Optical Phenomenon called Play of Color.Opal Stones with Play of Color are called Fire Opal.Opal is Birthstone of October month.',
    product_return:'If you are not satisfied with this product,return it for a refund.we will always care our customer..!',
    product_weight:'The model(weight 3kg)',
    product_material:' Hard-Material' },
     {
    product_id:'7', 
    product_image: "assets/img/turquoise_1.jpg",
    product_title:'Turquoise Stone',
    product_price: 2650,
    product_offer: 2850,
    product_ship: 30,
    product_disc:'30% off',
    product_details:'Turquoise is an Opaque Gemstone, called Firoza in Hindi.Turquoise color ranges from Blue to Green, like Sky Blue, Bluish Green to Greenish Blue.Turquoise is liked for its attractive color & Healing Properties.',
    product_return:'If you are not satisfied with this product,return it for a refund.we will always care our customer..!',
    product_weight:'The model(weight 3kg)',
    product_material:' Hard-Material' },
     {
    product_id:'8', 
    product_image: "assets/img/yellowsaphire.jpeg",
    product_title:'Yellow Saphire Stone',
    product_price: 1550,
    product_offer: 1950,
    product_ship: 30,
    product_disc:'30% off',
    product_details:'Yellow Sapphire is associated with Jupiter (Guru) Planet as per Indian Astrology.Yellow Sapphire Stone (variety of Corundum mineral species) is called Pukhraj in Hindi.Yellow Sapphire Gemstone is worn in Ring or Pendant made of Yellow metal for Astrological reasons.',
    product_return:'If you are not satisfied with this product,return it for a refund.we will always care our customer..!',
    product_weight:'The model(weight 3kg)',
    product_material:' Hard-Material' },
     {
    product_id:'9', 
    product_image: "assets/img/pearl.jpg",
    product_title:'Pearl',
    product_price: 1350,
    product_offer: 1650,
    product_ship: 30,
    product_disc:'30% off',
    product_details:'Pearl is Birthstone for September month.Blue Sapphire is liked for its Pure Blue hue & good durability.Blue Sapphire or simply Sapphire is a Precious Stone, called Neelam in Hindi.',
    product_return:'If you are not satisfied with this product,return it for a refund.we will always care our customer..!',
    product_weight:'The model(weight 3kg)',
    product_material:' Hard-Material'},
     {
    product_id:'10', 
    product_image: "assets/img/daimond.jpg",
    product_title:'Daimond',
    product_price: 1250,
    product_offer: 1550,
    product_ship: 30,
    product_disc:'30% off',
    product_details:'Diamond is the most Precious & Desirable Gemstone, it is also the hardest Natural material on Earth,Diamond looks really Brilliant due to its extreme Optical Properties like Refractive Index & Dispersion Diamond is Birthstone of April Month.',
    product_return:'If you are not satisfied with this product,return it for a refund.we will always care our customer..!',
    product_weight:'The model(weight 3kg)',
    product_material:' Hard-Material' },
     {
    product_id:'11', 
    product_image: "assets/img/coral.jpg",
    product_title:'Coral',
    product_price: 1650,
    product_offer: 2550,
    product_ship: 30,
    product_disc:'30% off' ,
    product_details:'Coral is an organic Gemstone, called Moonga in Hindi.Red Coral is desirable for its Color & Astrological Benefits.',
    product_return:'If you are not satisfied with this product,return it for a refund.we will always care our customer..!',
    product_weight:'The model(weight 3kg)',
    product_material:' Hard-Material'},
     {
    product_id:'12', 
    product_image: "assets/img/Aquamarine.jpg",
    product_title:'Aquamarine',
    product_price: 1350,
    product_offer: 1750,
    product_ship: 30,
    product_disc:'30% off' ,
    product_details:'Aquamarine is Birthstone for September month.Blue Sapphire is liked for its Pure Blue hue & good durability.Blue Sapphire or simply Sapphire is a Precious Stone, called Neelam in Hindi.',
    product_return:'If you are not satisfied with this product,return it for a refund.we will always care our customer..!',
    product_weight:'The model(weight 3kg)',
    product_material:' Hard-Material'},
     {
    product_id:'13', 
    product_image: "assets/img/Citrine.jpg",
    product_title:'Citrine',
    product_price: 2500,
    product_offer: 3050,
    product_ship: 30,
    product_disc:'30% off' ,
    product_details:'Citrine is Birthstone for September month.Blue Sapphire is liked for its Pure Blue hue & good durability.Blue Sapphire or simply Sapphire is a Precious Stone, called Neelam in Hindi.',
    product_return:'If you are not satisfied with this product,return it for a refund.we will always care our customer..!',
    product_weight:'The model(weight 3kg)',
    product_material:' Hard-Material'},
     {
    product_id:'14', 
    product_image: "assets/img/Rubellite.jpg",
    product_title:'Rubellite',
    product_price: 1750,
    product_offer: 1950,
    product_ship: 30,
    product_disc:'30% off',
    product_details:'Rubellite is Birthstone for September month.Blue Sapphire is liked for its Pure Blue hue & good durability.Blue Sapphire or simply Sapphire is a Precious Stone, called Neelam in Hindi.',
    product_return:'If you are not satisfied with this product,return it for a refund.we will always care our customer..!',
    product_weight:'The model(weight 3kg)',
    product_material:' Hard-Material' },
     {
    product_id:'15', 
    product_image: "assets/img/lapis-lazuli.jpg",
    product_title:'lapis-lazuli',
    product_price: 1250,
    product_offer: 1650,
    product_ship: 30,
    product_disc:'30% off',
    product_details:'lapis-lazuli is Birthstone for September month.Blue Sapphire is liked for its Pure Blue hue & good durability.Blue Sapphire or simply Sapphire is a Precious Stone, called Neelam in Hindi.',
    product_return:'If you are not satisfied with this product,return it for a refund.we will always care our customer..!',
    product_weight:'The model(weight 3kg)',
    product_material:' Hard-Material' },
     {
    product_id:'16', 
    product_image: "assets/img/peridot.jpg",
    product_title:'Periodt',
    product_price: 1550,
    product_offer: 1850,
    product_ship: 30,
    product_disc:'30% off',
    product_details:'peridot is Birthstone for September month.Blue Sapphire is liked for its Pure Blue hue & good durability.Blue Sapphire or simply Sapphire is a Precious Stone, called Neelam in Hindi.',
    product_return:'If you are not satisfied with this product,return it for a refund.we will always care our customer..!',
    product_weight:'The model(weight 3kg)',
    product_material:' Hard-Material' },
     {
    product_id:'17', 
    product_image: "assets/img/amethyst.jpg",
    product_title:'Amethyst',
    product_price: 1550,
    product_offer: 1650,
    product_ship: 30,
    product_disc:'30% off',
    product_details:'Amethyst is Birthstone for September month.Blue Sapphire is liked for its Pure Blue hue & good durability.Blue Sapphire or simply Sapphire is a Precious Stone, called Neelam in Hindi.',
    product_return:'If you are not satisfied with this product,return it for a refund.we will always care our customer..!',
    product_weight:'The model(weight 3kg)',
    product_material:' Hard-Material' },
     {
    product_id:'18',
    product_image: "assets/img/rose-quartz_1.jpg",
    product_title:'rose quartz',
    product_price: 1350,
    product_offer: 1600,
    product_ship: 30,
    product_disc:'30% off' ,
    product_details:'Quartz is Birthstone for September month.Blue Sapphire is liked for its Pure Blue hue & good durability.Blue Sapphire or simply Sapphire is a Precious Stone, called Neelam in Hindi.',
    product_return:'If you are not satisfied with this product,return it for a refund.we will always care our customer..!',
    product_weight:'The model(weight 3kg)',
    product_material:' Hard-Material'},
     {
    product_id:'19', 
    product_image: "assets/img/Iolite_1.jpg",
    product_title:'Iolite',
    product_price: 1250,
    product_offer: 1500,
    product_ship: 30,
    product_disc:'30% off',
    product_details:'Iolite is Birthstone for September month.Blue Sapphire is liked for its Pure Blue hue & good durability.Blue Sapphire or simply Sapphire is a Precious Stone, called Neelam in Hindi.',
    product_return:'If you are not satisfied with this product,return it for a refund.we will always care our customer..!',
    product_weight:'The model(weight 3kg)',
    product_material:' Hard-Material' },
     {
    product_id:'20', 
    product_image: "assets/img/moonstone_1.jpg",
    product_title:'Moonstone',
    product_price: 1850,
    product_offer: 1650,
    product_ship: 30,
    product_disc:'30% off',
    product_details:'Moonstone is Birthstone for September month.Blue Sapphire is liked for its Pure Blue hue & good durability.Blue Sapphire or simply Sapphire is a Precious Stone, called Neelam in Hindi.',
    product_return:'If you are not satisfied with this product,return it for a refund.we will always care our customer..!',
    product_weight:'The model(weight 3kg)',
    product_material:' Hard-Material' },
      {
    product_id:'21',
    product_image: "assets/img/malachite.jpg",
    product_title:'malachite',
    product_price: 1550,
    product_offer: 1750,
    product_ship: 30,
    product_disc:'30% off' ,
    product_details:'Malachite is Birthstone for September month.Blue Sapphire is liked for its Pure Blue hue & good durability.Blue Sapphire or simply Sapphire is a Precious Stone, called Neelam in Hindi.',
    product_return:'If you are not satisfied with this product,return it for a refund.we will always care our customer..!',
    product_weight:'The model(weight 3kg)',
    product_material:' Hard-Material'},
      {
    product_id:'22', 
    product_image: "assets/img/Tanzanite.jpg",
    product_title:'Tanzanite',
    product_price: 1350,
    product_offer: 1550,
    product_ship: 30,
    product_disc:'30% off' ,
    product_details:'Tanzanite is Birthstone for September month.Blue Sapphire is liked for its Pure Blue hue & good durability.Blue Sapphire or simply Sapphire is a Precious Stone, called Neelam in Hindi.',
    product_return:'If you are not satisfied with this product,return it for a refund.we will always care our customer..!',
    product_weight:'The model(weight 3kg)',
    product_material:' Hard-Material'},
      {
    product_id:'23', 
    product_image: "assets/img/gemstone-chart-whitesapphire.jpg",
    product_title:'White Sapphire',
    product_price: 1600,
    product_offer: 1900,
    product_ship: 30,
    product_disc:'30% off' ,
    product_details:'White Sapphire is colorless variety of mineral Corundum.White Sapphire has better Luster than that of White Topaz & White Rock Crystal due to higher Refractive Index.White Sapphire is also more durable than White Topaz & White Rock Crystal due to more Hardness.',
    product_return:'If you are not satisfied with this product,return it for a refund.we will always care our customer..!',
    product_weight:'The model(weight 3kg)',
    product_material:' Hard-Material'},
     {
    product_id:'24', 
    product_image: "assets/img/carnelian_1.jpg",
    product_title:'Carnelian',
    product_price: 1450,
    product_offer: 1550,
    product_ship: 30,
    product_disc:'30% off' ,
    product_details:'Carnelian is Birthstone for September month.Blue Sapphire is liked for its Pure Blue hue & good durability.Blue Sapphire or simply Sapphire is a Precious Stone, called Neelam in Hindi.',
    product_return:'If you are not satisfied with this product,return it for a refund.we will always care our customer..!',
    product_weight:'The model(weight 3kg)',
    product_material:' Hard-Material'},
      {
    product_id:'25', 
    product_image: "assets/img/blue-topaz.jpg",
    product_title:'Blue Topaz',
    product_price: 1350,
    product_offer: 1650,
    product_ship: 30,
    product_disc:'30% off',
    product_details:'Blue Topaz is Birthstone for September month.Blue Sapphire is liked for its Pure Blue hue & good durability.Blue Sapphire or simply Sapphire is a Precious Stone, called Neelam in Hindi.',
    product_return:'If you are not satisfied with this product,return it for a refund.we will always care our customer..!',
    product_weight:'The model(weight 3kg)',
    product_material:' Hard-Material' },
       {
    product_id:'26', 
    product_image: "assets/img/purple-sapphire.jpg",
    product_title:'Purple-Sapphire',
    product_price: 1220,
    product_offer: 1665,
    product_ship: 30,
    product_disc:'30% off' ,
    product_details:'purple-Sapphire is Birthstone for September month.Blue Sapphire is liked for its Pure Blue hue & good durability.Blue Sapphire or simply Sapphire is a Precious Stone, called Neelam in Hindi.',
    product_return:'If you are not satisfied with this product,return it for a refund.we will always care our customer..!',
    product_weight:'The model(weight 3kg)',
    product_material:' Hard-Material'},
      {
    product_id:'27', 
    product_image: "assets/img/prehnite1_1.jpg",
    product_title:'Prehnite',
    product_price: 1350,
    product_offer: 2500,
    product_ship: 30,
    product_disc:'30% off',
    product_details:'Prehnite is Birthstone for September month.Blue Sapphire is liked for its Pure Blue hue & good durability.Blue Sapphire or simply Sapphire is a Precious Stone, called Neelam in Hindi.',
    product_return:'If you are not satisfied with this product,return it for a refund.we will always care our customer..!',
    product_weight:'The model(weight 3kg)',
    product_material:' Hard-Material' },
      {
    product_id:'28', 
    product_image: "assets/img/Labradorite.jpg",
    product_title:'Labradorite',
    product_price: 1850,
    product_offer: 1650,
    product_ship: 30,
    product_disc:'30% off',
    product_details:'Labradorite is a grey to greyish black feldspar, which displays a remarkable optical phenomenon unique to it, known as Labradorescence.',
    product_return:'If you are not satisfied with this product,return it for a refund.we will always care our customer..!',
    product_weight:'The model(weight 3kg)',
    product_material:' Hard-Material' },
      {
    product_id:'29', 
    product_image: "assets/img/rhodochrosite.jpg",
    product_title:'RhodoChrosite',
    product_price: 1850,
    product_offer: 1960,
    product_ship: 30,
    product_disc:'30% off',
    product_details:'RhodoChrosite is Birthstone for September month.Blue Sapphire is liked for its Pure Blue hue & good durability.Blue Sapphire or simply Sapphire is a Precious Stone, called Neelam in Hindi.',
    product_return:'If you are not satisfied with this product,return it for a refund.we will always care our customer..!',
    product_weight:'The model(weight 3kg)',
    product_material:' Hard-Material' },
      {
    product_id:'30', 
    product_image: "assets/img/smoky-quartz.jpg",
    product_title:'Smoky Quartz',
    product_price: 1950,
    product_offer: 2250,
    product_ship: 30,
    product_disc:'30% off',
    product_details:'Smoke is Birthstone for September month.Blue Sapphire is liked for its Pure Blue hue & good durability.Blue Sapphire or simply Sapphire is a Precious Stone, called Neelam in Hindi.',
    product_return:'If you are not satisfied with this product,return it for a refund.we will always care our customer..!',
    product_weight:'The model(weight 3kg)',
    product_material:' Hard-Material' }
    ];
    
}